# Compiler to use (using CXX for C++)
CXX ?= g++

# Compiler flags (using CXXFLAGS for C++ and adding dependency generation)
CXXFLAGS = -Wall -Wextra -std=c++17 -MMD -MP
DEBUG_FLAGS = -g
ASAN_FLAGS = -fsanitize=address -fno-omit-frame-pointer

# Linker flags (needed for ASan)
LDFLAGS = 
ASAN_LDFLAGS = -fsanitize=address

# Target executable name
TARGET = test

# Source files
SRC = test.cpp utility.cpp

# Object files and auto-generated dependency files
OBJ = $(SRC:.cpp=.o)
DEPS = $(SRC:.cpp=.d)

# External library directories
DOCTEST_DIR = external/doctest
FAKEIT_DIR = external/fakeit
NANOBENCH_MARTINUS_DIR = external/nanobench
NANOBENCH_ABEL_DIR = external/nanoBench
STB_DIR = external/stb
JSON_DIR = external/json

# Include paths for each library
INCLUDES = -I$(DOCTEST_DIR)/doctest/ \
           -I$(FAKEIT_DIR)/single_header/doctest \
           -I$(NANOBENCH_MARTINUS_DIR)/src/include \
           -I$(STB_DIR) \
           -I$(JSON_DIR)/include/

# Default target
all: $(TARGET)

# Link object files to create the executable
$(TARGET): $(OBJ)
	$(CXX) $(LDFLAGS) $(OBJ) -o $(TARGET)

# Compile source files and generate .d dependency files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# Include dependency rules generated by compiler
-include $(DEPS)

# Debug target: build with debugging symbols
debug: CXXFLAGS += $(DEBUG_FLAGS)
debug: $(TARGET)

# ASan target: build with AddressSanitizer and debugging symbols
asan: CXXFLAGS += $(DEBUG_FLAGS) $(ASAN_FLAGS)
asan: LDFLAGS += $(ASAN_LDFLAGS)
asan: $(TARGET)

# Initialize and update existing external submodules
external:
	git submodule update --init --recursive

# Clean up build artifacts and dependency tracking files
clean:
	rm -f $(OBJ) $(DEPS) $(TARGET)

.PHONY: all debug asan external clean

